import Head from 'next/head'
import Link from 'next/link'
import { FC } from 'react'

const AppBar: FC = () => {
  return (
    <div className="text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default AppBar
