import type { NextPage } from 'next'
import Head from 'next/head'
import AppBar from '../components/AppBar'
import BottomBar from '../components/BottomBar'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <BottomBar />
    </div>
  )
}

export default Home
